spring:
  application:
    name: preferencesClient
  cloud:
    consul:
      config:
        host: 127.0.0.1
        port: 8500

server:
  port: 9090

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

